### ISSUE TITLE
Не нужно в DELETE передавать body - спорная практика

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/09-frontend#4]
https://github.com/lowerKamaCase/09-frontend/blob/bb841635d5417b0572eb53beb9e4e10e573bb875/app.js#L177-L181

**Comment by lowerKamaCase** [comment]
Действительно, я даже не обрабатывал этот id из body на сервере.
Нужный параметр передаю в URL'е

**Comment by lowerKamaCase** [comment]
Действительно, я даже не обрабатывал этот id из body на сервере.
Нужный параметр передаю в URL'е
