### ISSUE TITLE
Этот код дублируется, нужно вынести в отдельную функцию

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/09-frontend#6]
https://github.com/lowerKamaCase/09-frontend/blob/bb841635d5417b0572eb53beb9e4e10e573bb875/app.js#L306-L323

**Comment by lowerKamaCase** [comment]
Не понял с чем именно дублируется.
Есть мысль, что с кодом в setInterval.
Но в then'ах разные действия выполняются, а условиями не пойму как разграничить.
Как быть? :)

**Comment by coursar** [comment]
Передать то, что различается как стрелочную функцию )) делали же на паре
